// The MIT License
//
// Copyright (c) 2020 Temporal Technologies Inc.  All rights reserved.
//
// Copyright (c) 2020 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by MockGen. DO NOT EDIT.
// Source: ownership.go

// Package shard is a generated GoMock package.
package shard

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockshardAcquirer is a mock of shardAcquirer interface.
type MockshardAcquirer struct {
	ctrl     *gomock.Controller
	recorder *MockshardAcquirerMockRecorder
}

// MockshardAcquirerMockRecorder is the mock recorder for MockshardAcquirer.
type MockshardAcquirerMockRecorder struct {
	mock *MockshardAcquirer
}

// NewMockshardAcquirer creates a new mock instance.
func NewMockshardAcquirer(ctrl *gomock.Controller) *MockshardAcquirer {
	mock := &MockshardAcquirer{ctrl: ctrl}
	mock.recorder = &MockshardAcquirerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockshardAcquirer) EXPECT() *MockshardAcquirerMockRecorder {
	return m.recorder
}

// acquireShards mocks base method.
func (m *MockshardAcquirer) acquireShards(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "acquireShards", arg0)
}

// acquireShards indicates an expected call of acquireShards.
func (mr *MockshardAcquirerMockRecorder) acquireShards(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "acquireShards", reflect.TypeOf((*MockshardAcquirer)(nil).acquireShards), arg0)
}
